// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskAlreadyMedia.Infrasructure;

#nullable disable

namespace TestTaskAlreadyMedia.Infrasructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501085036_CreateNasaObjectsTable")]
    partial class CreateNasaObjectsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTaskAlreadyMedia.Infrasructure.Models.NasaObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<decimal[]>("Coordinates")
                        .HasColumnType("numeric[]");

                    b.Property<string>("Fall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeolocationType")
                        .HasColumnType("text");

                    b.Property<decimal>("Mass")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NasaId")
                        .HasColumnType("integer");

                    b.Property<string>("Recclass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Reclat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Reclong")
                        .HasColumnType("numeric");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("NasaObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
